---

- name: Deploy the osbuild repository
  yum_repository:
    name: osbuild-mock
    baseurl: http://osbuild-composer-repos.s3-website.us-east-2.amazonaws.com/osbuild/osbuild-composer/master/5ab8b59/rhel83_x86_64
    enabled: yes
    gpgcheck: no
    priority: 5

- name: Install required packages
  dnf:
    name:
      - cockpit
      - cockpit-composer
      - composer-cli
      - osbuild
      - osbuild-composer

- name: Start services
  systemd:
    name:
      - osbuild-composer.socket
      - cockpit.socket
    state: started
    enabled: yes

- name: Check API status
  command: "{{ item }}"
  loop:
    - composer-cli status show
    - composer-cli sources list