---

- hosts: localhost
  vars:
    ansible_connection: local
    flavor_name: ci.m1.medium
    image_id: 7bb8b994-d7e8-4a77-b28a-84aad5dc0b26
  tasks:

    - name: Authenticate to our OpenStack cloud
      os_auth:
      register: auth_result

    - name: Verify that the base image exists
      os_image_info:
        image: "{{ image_id }}"
      register: image_data

    - name: Print image details
      debug:
        var: image_data