pipeline {
    agent none

    environment {
        // Colorful Ansible always looks nicer.
        ANSIBLE_FORCE_COLOR="True"
        // Time each task and display stdout as YAML (easier to read).
        ANSIBLE_LOAD_CALLBACK_PLUGINS="True"
        ANSIBLE_CALLBACK_WHITELIST="profile_tasks"
        ANSIBLE_STDOUT_CALLBACK="yaml"
        // Don't display those ugly purple deprecation warnings.
        ANSIBLE_DEPRECATION_WARNINGS="False"
        // Our host keys are constantly changing.
        ANSIBLE_HOST_KEY_CHECKING="False"
        // Enable ssh pipelining for faster deployments to remote nodes.
        ANSIBLE_PIPELINING="True"
    }

    options {
        ansiColor('xterm')
        timeout(
            time: 3,
            unit: "HOURS"
        )
        timestamps()
    }
    stages {

        stage("Prepare 🤔") {
            agent { label "schutzbot" }
            steps {
                sh (
                    label: "Get environment variables",
                    script: "env | sort"
                )
            }
        }

        stage("Deploy 🚀") {
            agent { label "f31cloudbase || f32cloudbase" }
            environment {
                OPENSTACK_CREDS = credentials("psi-openstack-clouds-yaml")
            }
            steps {
                sh (
                    label: "Install Ansible",
                    script: "sudo dnf -y install ansible"
                )
                sh (
                    label: "Deploy",
                    script: "ansible-playbook -i localhost, deploy.yml"
                )
            }
        }

    }
}