---

- name: Register with staging RHN
  command: |
    subscription-manager register \
        --username={{ rhn_registration_username }} \
        --password={{ rhn_registration_password }} \
        --serverurl=subscription.rhsm.stage.redhat.com \
        --baseurl=cdn.stage.redhat.com \
        --release=8.2 \
        --auto-attach \
        --force
  register: rhn_registration
  until: rhn_registration is success
  retries: 5
  delay: 10

- name: Add Code Ready Builder repository
  command: |
    subscription-manager repos \
    --enable=codeready-builder-for-rhel-8-x86_64-rpms
  register: add_repo
  until: add_repo is success
  retries: 5
  delay: 10

- name: Ensure instance is fully updated
  dnf:
    name: "*"
    state: latest